// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProjetoModelo.Infra.Data.Context;
using System;

namespace ProjetoModelo.Infra.Data.Migrations
{
    [DbContext(typeof(ProjetoModeloContext))]
    partial class ProjetoModeloContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoModelo.Domain.Entities.Commodity", b =>
                {
                    b.Property<int>("CommodityID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<int>("DisciplinaID");

                    b.Property<string>("Nome");

                    b.Property<int>("TipoMaoObraID");

                    b.HasKey("CommodityID");

                    b.HasIndex("DisciplinaID");

                    b.HasIndex("TipoMaoObraID");

                    b.ToTable("Commodity");
                });

            modelBuilder.Entity("ProjetoModelo.Domain.Entities.Disciplina", b =>
                {
                    b.Property<int>("DisciplinaID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Nome");

                    b.HasKey("DisciplinaID");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("ProjetoModelo.Domain.Entities.TipoMaoObra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(150);

                    b.HasKey("ID");

                    b.ToTable("TipoMaoObra");
                });

            modelBuilder.Entity("ProjetoModelo.Domain.Entities.Commodity", b =>
                {
                    b.HasOne("ProjetoModelo.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("Commodities")
                        .HasForeignKey("DisciplinaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjetoModelo.Domain.Entities.TipoMaoObra", "TipoMaoDeObra")
                        .WithMany("Commodities")
                        .HasForeignKey("TipoMaoObraID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
